const chatList = [
  {
    id: 1,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-1.8d5d7e809a27a1717ed1.jpg",
    name: "Ashley Silva",
    message: "Good Morning",
    time: "04:32 PM",
    unreadcount: 4,
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 2,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-2.58874a6f667b9b04ce55.jpg",
    name: "Misty Taylor",
    message: "Okay, Byy",
    time: "02:49 PM",
    unreadcount: 1,
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 3,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-3.36fbb9e4e257ecafc0da.jpg",
    name: "Scott Wilson",
    message: "Yeah everything is fine...",
    time: "12:04 PM",
    unreadcount: 8,
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 4,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-4.e2de47eb85d48b966ed3.jpg",
    name: "Patricia Wilson",
    message: "Hey! there I m available",
    time: "11:11 AM",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 5,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-5.a991bb8ecd885f209314.jpg",
    name: "Allyson Wigfall",
    message: "I have finished it! See you so",
    time: "09:24 AM",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 6,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-6.e43b0230b936ad37e477.jpg",
    name: "Martha Griffin",
    message: "Wow that's great",
    time: "16/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 7,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-10.2a8fb05317cf7cda75ee.jpg",
    name: "Mark Sargent",
    message: "Nice to meet you",
    time: "16/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 8,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-8.64cbb563832bd489e1ef.jpg",
    name: "Ray Stricklin",
    message: "Hey, hi Ray stricklin",
    time: "16/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 9,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-9.ac7d94bc06649bd511ae.jpg",
    name: "Frank Taylor",
    message: "Happy holidays",
    time: "15/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time4: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time5: "09:07 AM" },
    ],
  },
  {
    id: 10,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-10.2a8fb05317cf7cda75ee.jpg",
    name: "Karla Bassco",
    message: "Okay, sure",
    time: "15/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 11,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-2.58874a6f667b9b04ce55.jpg",
    name: "Sally McPherson",
    message: "Thanks",
    time: "14/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
  {
    id: 12,
    img: "https://themes.themesbrand.com/hybrix/react-material/light/static/media/avatar-3.36fbb9e4e257ecafc0da.jpg",
    name: "Lizzie Beil",
    message: "Our next meeting tomorrow 10.00 AM",
    time: "13/11",
    chats: [
      { sender: "Ashley Silva", message1: "Good morning 😊", time1: "09:07 AM" },
      { sender: "You", message2: "Good morning, How are you? What about our next meeting?", time2: "09:08 AM" },
      { sender: "Ashley Silva", message3: "Yeah everything is fine. Our next meeting tomorrow at 10.00 AM", time3: "09:10 AM" },
      { sender: "Ashley Silva", message4: "Hey, I'm going to meet a friend of mine at the department store. I have to buy some presents for my parents 🎁.", time: "09:10 AM" },
      { sender: "Ashley Silva", message5: "Wow that's great", time4: "09:07 AM" },
    ],
  },
]

export default chatList;